import {
  Box, Button, Grid,
  GridItem, HStack, Link, Text, VStack
} from "@chakra-ui/react";
import Head from "next/head";
import Berlangganan from "@/src/components/Berlangganan";
import NextLink from "next/link";

export default function Blog() {
  return (
    <>
      <Head>
        <title>Blog detail</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <VStack w={["100%"]} alignItems={["flex-start"]} position={["relative"]}>
        <Grid
          w={["100%"]}
          height={["100%"]}
          templateColumns="repeat(10, 1fr)"
          // templateRows="repeat(2, 1fr)"
          paddingY={["20px"]}
          gap={["0 50px"]}
        >
          {/* Left */}
          <GridItem
            borderRightWidth={["1px"]}
            borderRightColor={["rgba(0,0,0, 0.2)"]}
            paddingX={["20px"]}
            height={["100%"]}
            paddingTop={["20px"]}
            paddingBottom={["100px"]}
            position={["sticky"]}
            top={["105px"]}
            left={["0"]}
            bottom={["0"]}
          >
            <VStack
              w={["100%"]}
              height={["100%"]}
              alignItems={["center"]}
              spacing={["48px"]}
            >
              <Button>❤</Button>
              <Button>✉</Button>
              <Button>✈</Button>
            </VStack>
          </GridItem>

          {/* Mid */}
          <GridItem colSpan={6} rowSpan={2}>
            <VStack
              w={["100%"]}
              h={["100%"]}
              alignItems={["flex-start"]}
              spacing={["30px"]}
            >
              {/* Header */}
              <Link as={NextLink} href="/" width={["100%"]}>
                <Box
                  w={["100%"]}
                  height={["350px"]}
                  backgroundColor={["#D9D9D9"]}
                  flexShrink={[0]}
                />
              </Link>

              {/* Body */}

              <VStack
                w={["100%"]}
                height={["100%"]}
                alignItems={["flex-start"]}
                spacing={["40px"]}
              >
                <VStack
                  w={["100%"]}
                  height={["100%"]}
                  alignItems={["flex-start"]}
                >
                  <Text
                    as="h1"
                    fontSize={["5xl"]}
                    lineHeight={["1.2em"]}
                    fontWeight={["bold"]}
                  >
                    Membuat sesuatu yang bermanfaat
                  </Text>

                  <Text fontSize={["xl"]}>
                    Desember 04, 2022 - 3 Minutes Reading
                  </Text>
                  <HStack
                    w={["100%"]}
                    height={["100%"]}
                    alignItems={["flex-start"]}
                  >
                    <Link
                      as={NextLink}
                      href="/"
                      fontWeight={["bold"]}
                      color="brand.50"
                      fontSize={["xl"]}
                    >
                      #SELF IMPROVEMENT
                    </Link>
                    <Link
                      as={NextLink}
                      href="/"
                      fontWeight={["bold"]}
                      color="brand.50"
                      fontSize={["xl"]}
                    >
                      #BISNIS
                    </Link>
                  </HStack>
                </VStack>
                <VStack w={["100%"]} alignItems={["flex-start"]}>
                  <Text fontSize={["2xl"]}>
                    Membuat sesuatu yang bermanfaat bertujuan agar kita dapat
                    memanfaatkan sesuatu yang mungkin akan kita butuhkan dimasa
                    depan. Sesuatu yang bermanfaat bagi diri kita sendiri
                    benarkan ? Membuat sesuatu yang bermanfaat bertujuan agar
                    kita dapat memanfaatkan sesuatu yang mungkin akan kita
                    butuhkan dimasa depan. Sesuatu yang bermanfaat bagi diri
                    kita sendiri benarkan ? Membuat sesuatu yang bermanfaat
                    bertujuan agar kita dapat memanfaatkan sesuatu yang mungkin
                    akan kita butuhkan dimasa depan. Sesuatu yang bermanfaat
                    bagi diri kita sendiri benarkan ?
                  </Text>

                  <Text fontSize={["4xl"]} fontWeight={["bold"]}>
                    Heading 1
                  </Text>
                  <Text fontSize={["3xl"]} fontWeight={["bold"]}>
                    Heading 2
                  </Text>
                  <Text fontSize={["2xl"]} fontWeight={["bold"]}>
                    Heading 3
                  </Text>
                  <Text fontSize={["xl"]} fontWeight={["bold"]}>
                    Heading 4
                  </Text>
                  <Text fontSize={["2xl"]}>
                    Membuat sesuatu yang bermanfaat bertujuan agar kita dapat
                    memanfaatkan sesuatu yang mungkin akan kita butuhkan dimasa
                    depan. Sesuatu yang bermanfaat bagi diri kita sendiri
                    benarkan ? Membuat sesuatu yang bermanfaat bertujuan agar
                    kita dapat memanfaatkan sesuatu yang mungkin akan kita
                    butuhkan dimasa depan. Sesuatu yang bermanfaat bagi diri
                    kita sendiri benarkan ? Membuat sesuatu yang bermanfaat
                    bertujuan agar kita dapat memanfaatkan sesuatu yang mungkin
                    akan kita butuhkan dimasa depan. Sesuatu yang bermanfaat
                    bagi diri kita sendiri benarkan ?
                  </Text>
                  <Text fontSize={["2xl"]}>
                    Membuat sesuatu yang bermanfaat bertujuan agar kita dapat
                    memanfaatkan sesuatu yang mungkin akan kita butuhkan dimasa
                    depan. Sesuatu yang bermanfaat bagi diri kita sendiri
                    benarkan ? Membuat sesuatu yang bermanfaat bertujuan agar
                    kita dapat memanfaatkan sesuatu yang mungkin akan kita
                    butuhkan dimasa depan. Sesuatu yang bermanfaat bagi diri
                    kita sendiri benarkan ? Membuat sesuatu yang bermanfaat
                    bertujuan agar kita dapat memanfaatkan sesuatu yang mungkin
                    akan kita butuhkan dimasa depan. Sesuatu yang bermanfaat
                    bagi diri kita sendiri benarkan ?
                  </Text>
                </VStack>
              </VStack>

              <Berlangganan />
            </VStack>
          </GridItem>

          {/* Right */}
          <GridItem
            colSpan={3}
            position={["sticky"]}
            top={["105px"]}
            left={["0"]}
            bottom={["0"]}
            paddingTop={["20px"]}
          >
            <VStack
              w={["100%"]}
              h={["100%"]}
              alignItems={["flex-start"]}
              spacing={["100px"]}
            >
              {/* Card */}
              <VStack
                w={["100%"]}
                h={["max-content"]}
                alignItems={["flex-start"]}
                spacing={["64px"]}
              >
                {/* Other Article */}
                <VStack
                  w={["100%"]}
                  height={["max-content"]}
                  alignItems={["flex-start"]}
                  spacing={["32px"]}
                >
                  <Text
                    as="h2"
                    color="brand.50"
                    fontSize={["3xl"]}
                    fontWeight={["bold"]}
                    lineHeight={["1.2em"]}
                  >
                    Rekomendasi artikel dengan tag yang sama
                  </Text>

                  <VStack
                    w={["100%"]}
                    height={["100%"]}
                    alignItems={["flex-start"]}
                    spacing={["10px"]}
                  >
                    <VStack w={["100%"]} alignItems={["flex-start"]}>
                      <Link
                        fontSize={["2xl"]}
                        fontWeight={["bold"]}
                        as={NextLink}
                        href="/"
                      >
                        Cara membuat sesuatu
                      </Link>
                      <Text fontSize={["xl"]}>
                        Desember 04, 2022 - 3 Minutes Reading
                      </Text>
                      <HStack
                        w={["100%"]}
                        height={["100%"]}
                        alignItems={["flex-start"]}
                      >
                        <Link
                          as={NextLink}
                          href="/"
                          fontWeight={["bold"]}
                          color="brand.50"
                          fontSize={["xl"]}
                        >
                          #SELF IMPROVEMENT
                        </Link>
                        <Link
                          as={NextLink}
                          href="/"
                          fontWeight={["bold"]}
                          color="brand.50"
                          fontSize={["xl"]}
                        >
                          #BISNIS
                        </Link>
                      </HStack>
                    </VStack>
                    <VStack w={["100%"]} alignItems={["flex-start"]}>
                      <Link
                        fontSize={["2xl"]}
                        fontWeight={["bold"]}
                        as={NextLink}
                        href="/"
                      >
                        Cara membuat sesuatu
                      </Link>
                      <Text fontSize={["xl"]}>
                        Desember 04, 2022 - 3 Minutes Reading
                      </Text>
                      <HStack
                        w={["100%"]}
                        height={["100%"]}
                        alignItems={["flex-start"]}
                      >
                        <Link
                          as={NextLink}
                          href="/"
                          fontWeight={["bold"]}
                          color="brand.50"
                          fontSize={["xl"]}
                        >
                          #SELF IMPROVEMENT
                        </Link>
                        <Link
                          as={NextLink}
                          href="/"
                          fontWeight={["bold"]}
                          color="brand.50"
                          fontSize={["xl"]}
                        >
                          #BISNIS
                        </Link>
                      </HStack>
                    </VStack>
                    <VStack w={["100%"]} alignItems={["flex-start"]}>
                      <Link
                        fontSize={["2xl"]}
                        fontWeight={["bold"]}
                        as={NextLink}
                        href="/"
                      >
                        Cara membuat sesuatu
                      </Link>
                      <Text fontSize={["xl"]}>
                        Desember 04, 2022 - 3 Minutes Reading
                      </Text>
                      <HStack
                        w={["100%"]}
                        height={["100%"]}
                        alignItems={["flex-start"]}
                      >
                        <Link
                          as={NextLink}
                          href="/"
                          fontWeight={["bold"]}
                          color="brand.50"
                          fontSize={["xl"]}
                        >
                          #SELF IMPROVEMENT
                        </Link>
                        <Link
                          as={NextLink}
                          href="/"
                          fontWeight={["bold"]}
                          color="brand.50"
                          fontSize={["xl"]}
                        >
                          #BISNIS
                        </Link>
                      </HStack>
                    </VStack>
                  </VStack>
                </VStack>

                {/* Tags */}
                <VStack
                  w={["100%"]}
                  height={["max-content"]}
                  alignItems={["flex-start"]}
                  spacing={["32px"]}
                >
                  <Text
                    as="h2"
                    color="brand.50"
                    fontSize={["3xl"]}
                    fontWeight={["bold"]}
                    lineHeight={["1.2em"]}
                  >
                    Tags lainnya
                  </Text>

                  <VStack
                    w={["100%"]}
                    height={["100%"]}
                    alignItems={["flex-start"]}
                    spacing={["10px"]}
                  >
                    <Link
                      as={NextLink}
                      href="/"
                      fontWeight={["bold"]}
                      color="brand.50"
                      fontSize={["xl"]}
                    >
                      #SELF IMPROVEMENT
                    </Link>
                    <Link
                      as={NextLink}
                      href="/"
                      fontWeight={["bold"]}
                      color="brand.50"
                      fontSize={["xl"]}
                    >
                      #SELF MOVEMENT
                    </Link>
                    <Link
                      as={NextLink}
                      href="/"
                      fontWeight={["bold"]}
                      color="brand.50"
                      fontSize={["xl"]}
                    >
                      #SELF INDIVIDUALIS
                    </Link>
                  </VStack>
                </VStack>
              </VStack>
              {/* End Of Card */}
            </VStack>
          </GridItem>
        </Grid>
      </VStack>
    </>
  );
}
