import Head from "next/head";
import {
  Container,
  Flex,
  Text,
  Stack,
  Switch,
  HStack,
  VStack,
  Grid,
  GridItem,
  Box,
  Input,
  SimpleGrid,
  Button,
  Link,
} from "@chakra-ui/react";
// import Image from "next/image";
// import ProfileImage from "@/src/assets/images/img.jpg";
import NextLink from "next/link";
// import source_sans_3 from "@/src/constants/fonts/source_sans_3";

export default function Home() {
  return (
    <>
      <Head>
        <title>Blog</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <VStack w={["100%"]} alignItems={["flex-start"]} position={["relative"]}>
        <Container
          paddingY={["16px"]}
          maxW="container.xl"
          position={["sticky"]}
          top={["0"]}
          left={["0"]}
          right="0"
          bottom="0"
          backgroundColor={['white']}
          borderBottomColor={["rgba(0,0,0, 0.2)"]}
          borderBottomWidth={['1px']}
          zIndex={['100']}
          marginX={['0']}
        >
          <Flex justifyContent="space-between" align={["center"]}>
            <Text color="brand.50" fontSize={["5xl"]} fontWeight={["bold"]}>
              Elbi
            </Text>
            <Stack
              direction={["row"]}
              spacing={["32px"]}
              alignItems={["center"]}
            >
              <Text fontWeight={["semibold"]} color="" fontSize={["2xl"]}>
                About
              </Text>
              <Text
                fontWeight={["semibold"]}
                color="brand.50"
                fontSize={["2xl"]}
              >
                Blog
              </Text>
              <HStack
                alignItems={["center"]}
                justifyContent={["space-between"]}
                spacing={["10px"]}
              >
                <Text>🌞</Text>
                <Switch></Switch>
                <Text>🌙</Text>
              </HStack>
            </Stack>
          </Flex>
        </Container>
    
        <Grid 
          w={["100%"]} 
          height={['100%']} 
          templateColumns="repeat(3, 1fr)"
          templateRows="repeat(2, 1fr)"
          paddingY={["20px"]}>
          {/* Left */}
          <GridItem
            borderRightWidth={["1px"]}
            borderRightColor={["rgba(0,0,0, 0.2)"]}
            paddingX={["20px"]}
            height={["100%"]}
            paddingTop={["20px"]}
            paddingBottom={["100px"]}
            position={['sticky']}
            top={['105px']}
            left={['0']}
          >
            <VStack
              w={["100%"]}
              height={["100%"]}
              alignItems={["center"]}
              spacing={["60px"]}
            >
              <VStack
                w={["100%"]}
                height={["max-content"]}
                alignItems={["center"]}
                spacing={["10px"]}
              >
                <Text color="brand.50" fontSize={["4xl"]} fontWeight={["bold"]}>
                  Filter
                </Text>

                <VStack w={["100%"]} h={["100%"]} spacing={["20px"]}>
                  <VStack w={["100%"]} h={["100%"]} alignItems={["flex-start"]}>
                    <Text
                      color="brand.50"
                      fontSize={["2xl"]}
                      fontWeight={["bold"]}
                    >
                      Judul
                    </Text>
                    <HStack
                      w={["100%"]}
                      // borderWidth={["1px"]}
                      // borderColor={["brand.50"]}
                      borderRadius={["8px"]}
                      h={["100%"]}
                      spacing={[0]}
                      // _hover={{ opacity: ["0.8"] }}
                      // _focusVisible={{ borderWidth: ["2px"], opacity: ['1'] }}
                      // overflow={['hidden']}
                    >
                      <Input
                        data-peer=""
                        w={["70%"]}
                        borderColor={["brand.50"]}
                        _focusVisible={{ boxShadow: "0 0 1px #7e1aff" }}
                        _hover={{ borderColor: ["brand.600"] }}
                        borderRightRadius={["0"]}
                        borderLeftRadius={["8px"]}
                      ></Input>
                      <Button
                        w={["30%"]}
                        height={["100%"]}
                        bgColor={["brand.50"]}
                        cursor={["pointer"]}
                        color={["white"]}
                        borderRadius={[0]}
                        _hover={{ backgroundColor: "brand.500" }}
                        borderRightRadius={["8px"]}
                        borderLeftRadius={["0px"]}
                      >
                        Cari
                      </Button>
                    </HStack>
                  </VStack>

                  <VStack w={["100%"]} alignItems={["flex-start"]}>
                    <Text
                      color="brand.50"
                      fontSize={["2xl"]}
                      fontWeight={["bold"]}
                    >
                      Tags
                    </Text>
                    <HStack
                      w={["100%"]}
                      borderRadius={["50%"]}
                      h={["100%"]}
                      borderColor={["brand.50"]}
                    >
                      <Input
                        borderColor={["brand.50"]}
                        _focusVisible={{ boxShadow: "0 0 1px #7e1aff" }}
                        _hover={{ borderColor: ["brand.600"] }}
                        borderRadius={["8px"]}
                        w={["100%"]}
                      ></Input>
                    </HStack>
                  </VStack>

                  <SimpleGrid columns={2} w={["100%"]} spacingX={["30px"]}>
                    <VStack w={["100%"]} alignItems={["flex-start"]}>
                      <Text
                        color="brand.50"
                        fontSize={["2xl"]}
                        fontWeight={["bold"]}
                      >
                        Dari
                      </Text>
                      <HStack
                        w={["100%"]}
                        borderRadius={["50%"]}
                        h={["100%"]}
                        borderColor={["brand.50"]}
                      >
                        <Input
                          borderColor={["brand.50"]}
                          _focusVisible={{ boxShadow: "0 0 1px #7e1aff" }}
                          _hover={{ borderColor: ["brand.600"] }}
                          borderRadius={["8px"]}
                          w={["100%"]}
                          type="date"
                        ></Input>
                      </HStack>
                    </VStack>
                    <VStack w={["100%"]} alignItems={["flex-start"]}>
                      <Text
                        color="brand.50"
                        fontSize={["2xl"]}
                        fontWeight={["bold"]}
                      >
                        Sampai
                      </Text>
                      <HStack
                        w={["100%"]}
                        borderRadius={["50%"]}
                        h={["100%"]}
                        borderColor={["brand.50"]}
                      >
                        <Input
                          borderColor={["brand.50"]}
                          _focusVisible={{ boxShadow: "0 0 1px #7e1aff" }}
                          _hover={{ borderColor: ["brand.600"] }}
                          borderRadius={["8px"]}
                          w={["100%"]}
                          type="date"
                        ></Input>
                      </HStack>
                    </VStack>
                  </SimpleGrid>
                </VStack>
              </VStack>

              {/* Batas */}
              <Box
                w={["90%"]}
                height={["1px"]}
                bgColor={["rgba(0,0,0, 0.2)"]}
              ></Box>

              <VStack
                w={["100%"]}
                height={["max-content"]}
                spacing={["10px"]}
                alignItems={["flex-start"]}
              >
                {/* <Box
                  width={["150px"]}
                  height={["150px"]}
                  position={["relative"]}
                  overflow={["hidden"]}
                  borderRadius={["50%"]}
                  borderWidth={["5px"]}
                  borderColor={["brand.50"]}
                  flexShrink={["0"]}
                >
                  <Image
                    src={ProfileImage}
                    alt="profile picture"
                    placeholder="blur"
                    fill
                  />
                </Box> */}
                <Text
                  as="h1"
                  color={["brand.50"]}
                  fontWeight={["bold"]}
                  fontSize={["7xl"]}
                >
                  Halo
                </Text>
                <Text
                  as="p"
                  fontWeight={["semibold"]}
                  fontSize={["xl"]}
                >
                  Ayo berlangganan agar tidak ketinggalan update apapun dari
                  website ini
                </Text>
                <HStack
                  w={["100%"]}
                  // borderWidth={["1px"]}
                  // borderColor={["brand.50"]}
                  borderRadius={["8px"]}
                  h={["100%"]}
                  spacing={[0]}
                  // _hover={{ opacity: ["0.8"] }}
                  // _focusVisible={{ borderWidth: ["2px"], opacity: ['1'] }}
                  // overflow={['hidden']}
                >
                  <Input
                    data-peer=""
                    w={["70%"]}
                    borderColor={["brand.50"]}
                    _focusVisible={{ boxShadow: "0 0 1px #7e1aff" }}
                    _hover={{ borderColor: ["brand.600"] }}
                    borderRightRadius={["0"]}
                    borderLeftRadius={["8px"]}
                  ></Input>
                  <Button
                    w={["30%"]}
                    height={["100%"]}
                    bgColor={["brand.50"]}
                    cursor={["pointer"]}
                    color={["white"]}
                    borderRadius={[0]}
                    _hover={{ backgroundColor: "brand.500" }}
                    borderRightRadius={["8px"]}
                    borderLeftRadius={["0px"]}
                  >
                    Berlangganan
                  </Button>
                </HStack>
                <Text fontSize={["lg"]} fontWeight={["bold"]} color={['brand.50']}>
                  *Saya tidak akan mengirimkan email spam kepada anda*
                </Text>
              </VStack>
            </VStack>
          </GridItem>

          {/* Right */}
          <GridItem colSpan={2} rowSpan={2}>
            <VStack
              w={["100%"]}
              h={["100%"]}
              paddingX={["50px"]}
              alignItems={["flex-start"]}
              spacing={["100px"]}
            >
              {/* Card */}
              <VStack
                w={["100%"]}
                h={["max-content"]}
                alignItems={["flex-start"]}
                spacing={["30px"]}
              >
                {/* Header */}
                <Link as={NextLink} href="/" width={["100%"]}>
                  <Box
                    w={["90%"]}
                    height={["350px"]}
                    backgroundColor={["#D9D9D9"]}
                    flexShrink={[0]}
                  />
                </Link>

                {/* Body */}

                <VStack
                  w={["100%"]}
                  height={["100%"]}
                  alignItems={["flex-start"]}
                  spacing={["40px"]}
                >
                  <VStack
                    w={["100%"]}
                    height={["100%"]}
                    alignItems={["flex-start"]}
                  >
                    <Link
                      fontSize={["4xl"]}
                      fontWeight={["bold"]}
                      _hover={{
                        textDecoration: "underline",
                      }}
                      as={NextLink}
                      href="/"
                    >
                      Membuat sesuatu yang bermanfaat
                    </Link>

                    <Text fontSize={["xl"]}>
                      Desember 04, 2022 - 3 Minutes Reading
                    </Text>
                  </VStack>
                  <VStack w={["100%"]} alignItems={["flex-start"]}>
                    <Text fontSize={["2xl"]}>
                      Membuat sesuatu yang bermanfaat bertujuan agar kita dapat
                      memanfaatkan sesuatu yang mungkin akan kita butuhkan
                      dimasa depan. Sesuatu yang bermanfaat bagi diri kita
                      sendiri benarkan ?
                    </Text>
                    <Link
                      fontSize={["2xl"]}
                      fontWeight={["bold"]}
                      color={["brand.50"]}
                      _hover={{
                        textDecoration: "underline",
                      }}
                      as={NextLink}
                      href="/"
                    >
                      Klik disini untuk membaca selengkapnya.
                    </Link>
                  </VStack>
                </VStack>

                {/* Footer */}
                <HStack
                  w={["100%"]}
                  height={["100%"]}
                  alignItems={["flex-start"]}
                >
                  <Link
                    as={NextLink}
                    href="/"
                    fontWeight={["bold"]}
                    color="brand.50"
                    fontSize={["xl"]}
                  >
                    #SELF IMPROVEMENT
                  </Link>
                  <Link
                    as={NextLink}
                    href="/"
                    fontWeight={["bold"]}
                    color="brand.50"
                    fontSize={["xl"]}
                  >
                    #BISNIS
                  </Link>
                </HStack>
              </VStack>
              {/* End Of Card */}

              {/* Batas */}
              <Box
                w={["90%"]}
                height={["1px"]}
                bgColor={["rgba(0,0,0, 0.2)"]}
              ></Box>

              {/* Card */}
              <VStack
                w={["100%"]}
                h={["max-content"]}
                alignItems={["flex-start"]}
                spacing={["30px"]}
              >
                {/* Header */}
                <Link as={NextLink} href="/" width={["100%"]}>
                  <Box
                    w={["90%"]}
                    height={["350px"]}
                    backgroundColor={["#D9D9D9"]}
                    flexShrink={[0]}
                  />
                </Link>

                {/* Body */}

                <VStack
                  w={["100%"]}
                  height={["100%"]}
                  alignItems={["flex-start"]}
                  spacing={["40px"]}
                >
                  <VStack
                    w={["100%"]}
                    height={["100%"]}
                    alignItems={["flex-start"]}
                  >
                    <Link
                      fontSize={["4xl"]}
                      fontWeight={["bold"]}
                      _hover={{
                        textDecoration: "underline",
                      }}
                      as={NextLink}
                      href="/"
                    >
                      Membuat sesuatu yang bermanfaat
                    </Link>

                    <Text fontSize={["xl"]}>
                      Desember 04, 2022 - 3 Minutes Reading
                    </Text>
                  </VStack>
                  <VStack w={["100%"]} alignItems={["flex-start"]}>
                    <Text fontSize={["2xl"]}>
                      Membuat sesuatu yang bermanfaat bertujuan agar kita dapat
                      memanfaatkan sesuatu yang mungkin akan kita butuhkan
                      dimasa depan. Sesuatu yang bermanfaat bagi diri kita
                      sendiri benarkan ?
                    </Text>
                    <Link
                      fontSize={["2xl"]}
                      fontWeight={["bold"]}
                      color={["brand.50"]}
                      _hover={{
                        textDecoration: "underline",
                      }}
                      as={NextLink}
                      href="/"
                    >
                      Klik disini untuk membaca selengkapnya.
                    </Link>
                  </VStack>
                </VStack>

                {/* Footer */}
                <HStack
                  w={["100%"]}
                  height={["100%"]}
                  alignItems={["flex-start"]}
                >
                  <Link
                    as={NextLink}
                    href="/"
                    fontWeight={["bold"]}
                    color="brand.50"
                    fontSize={["xl"]}
                  >
                    #SELF IMPROVEMENT
                  </Link>
                  <Link
                    as={NextLink}
                    href="/"
                    fontWeight={["bold"]}
                    color="brand.50"
                    fontSize={["xl"]}
                  >
                    #BISNIS
                  </Link>
                </HStack>
              </VStack>
              {/* End Of Card */}

              {/* Batas */}
              <Box
                w={["90%"]}
                height={["1px"]}
                bgColor={["rgba(0,0,0, 0.2)"]}
              ></Box>

              {/* Card */}
              <VStack
                w={["100%"]}
                h={["max-content"]}
                alignItems={["flex-start"]}
                spacing={["30px"]}
              >
                {/* Header */}
                <Link as={NextLink} href="/" width={["100%"]}>
                  <Box
                    w={["90%"]}
                    height={["350px"]}
                    backgroundColor={["#D9D9D9"]}
                    flexShrink={[0]}
                  />
                </Link>

                {/* Body */}

                <VStack
                  w={["100%"]}
                  height={["100%"]}
                  alignItems={["flex-start"]}
                  spacing={["40px"]}
                >
                  <VStack
                    w={["100%"]}
                    height={["100%"]}
                    alignItems={["flex-start"]}
                  >
                    <Link
                      fontSize={["4xl"]}
                      fontWeight={["bold"]}
                      _hover={{
                        textDecoration: "underline",
                      }}
                      as={NextLink}
                      href="/"
                    >
                      Membuat sesuatu yang bermanfaat
                    </Link>

                    <Text fontSize={["xl"]}>
                      Desember 04, 2022 - 3 Minutes Reading
                    </Text>
                  </VStack>
                  <VStack w={["100%"]} alignItems={["flex-start"]}>
                    <Text fontSize={["2xl"]}>
                      Membuat sesuatu yang bermanfaat bertujuan agar kita dapat
                      memanfaatkan sesuatu yang mungkin akan kita butuhkan
                      dimasa depan. Sesuatu yang bermanfaat bagi diri kita
                      sendiri benarkan ?
                    </Text>
                    <Link
                      fontSize={["2xl"]}
                      fontWeight={["bold"]}
                      color={["brand.50"]}
                      _hover={{
                        textDecoration: "underline",
                      }}
                      as={NextLink}
                      href="/"
                    >
                      Klik disini untuk membaca selengkapnya.
                    </Link>
                  </VStack>
                </VStack>

                {/* Footer */}
                <HStack
                  w={["100%"]}
                  height={["100%"]}
                  alignItems={["flex-start"]}
                >
                  <Link
                    as={NextLink}
                    href="/"
                    fontWeight={["bold"]}
                    color="brand.50"
                    fontSize={["xl"]}
                  >
                    #SELF IMPROVEMENT
                  </Link>
                  <Link
                    as={NextLink}
                    href="/"
                    fontWeight={["bold"]}
                    color="brand.50"
                    fontSize={["xl"]}
                  >
                    #BISNIS
                  </Link>
                </HStack>
              </VStack>
              {/* End Of Card */}

            </VStack>
          </GridItem>
        </Grid>
      </VStack>
    </>
  );
}
